---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by rlfeng.
--- DateTime: 2024/1/5 14:56
---
--1.取出两个参数，分别为voucherID和userId
local voucherId = ARGV[1]
local userId = ARGV[2]
local stockKey = 'seckill:stock:' .. voucherId
local oderKey = 'seckill:oder:' .. voucherId
--2.判断库存是否充足，不足返回2
if(tonumber(redis.call('get', stockKey)) <= 0) then
    return 2
end
--3.判断当前用户是否买过
--3.1已购买，返回1
if(redis.call('sismember', oderKey, userId) == 1) then
    return 1
end
--3.2未购买：扣减库存，并将该用户id加入redis，返回0
redis.call('incrby', stockKey, -1)
redis.call('sadd', oderKey, userId)
return 0